
    server {
        listen 80; 

       
        location / {
            proxy_pass http://simple-ascii-frontend:3001; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

       
        location /api/ {
            proxy_pass http://simple-ascii-backend:3002/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            client_max_body_size 50M;
            proxy_read_timeout 300s;
        }
    }
